### ISSUE TITLE
slide_replace throws error

### ISSUE THREAD

**Issue by aghodsi** [pgimalac/pyptx-templar#1]
If I am not mistaken slide_replace takes a slide object and the replacement values in a dict (for **kwarg). 
so I call it like slide_replace(slide_object, **kwargs)

However, it is throwing the following error, am I missing something? I understand that the there is no _idx found, but given I am providing a slide index, and the signature doesn't support it, I guess there is a bug somewhere.

 ...
  File "\venv\lib\site-packages\pyptx_templar\placeholder.py", line 337, in slide_replace
    textframe_replace(sh.text_frame, **kwargs, _sl=slide)
  File "\venv\lib\site-packages\pyptx_templar\placeholder.py", line 215, in textframe_replace
    paragraph_replace(par, **kwargs, _tf=tf)
  File "\venv\lib\site-packages\pyptx_templar\placeholder.py", line 139, in paragraph_replace
    run_replace(run, **kwargs, _p=par)
  File "\venv\lib\site-packages\pyptx_templar\placeholder.py", line 107, in run_replace
    val = str(interp(m.group(1), **kwargs))
  File "\venv\lib\site-packages\pyptx_templar\placeholder.py", line 73, in interp
    context = f"[Slide {kwargs['_idx']}]"
KeyError: '_idx'

**Comment by pgimalac** [comment]
This issue is that I assumed that I would always have the slide index in the environment (because it's added automatically by `pres_replace`), but if you call any other function (here `textframe_replace`) then the index is not in the environment.

It's just used for logging purpose, so it shouldn't error if the index is not available.

A quick fix would be to provide the slide index in the environment, but I'll fix the issue anyway, thanks for reporting.

**Comment by pgimalac** [comment]
I pushed a fix, tell me if it works for you now. 

Note that I can't publish the new version on pypi right now (I should be able to do it tomorrow), so you have to use the GitHub version if you want to check.

**Comment by aghodsi** [comment]
That fixes the issue!
